### PR TITLE
Feature/tls server

### PR DESCRIPTION
**Pull request by scirner22**
Adds support for a `JAVA_OPTS` env var that gets put in the `java -jar` command. This allows you to configure a lot of things, but nycb will use it to configure server TLS at run time.

The added ports in the `Dockerfile` were needed because this runs with `--network host` for nycb. In that mode, you can't use `-p` flags at runtime to specify any port rules.

### Tests
- [x] Tested hostname verification and tls server side locally by creating a keystore, building, then running the container. I used curl to verify https was required and localhost didn't work without adding the `-k` flag. Hostname verification worked if I curled `coinsrv.dev` and added that to my `/etc/hosts` as well.

### CODE REVIEW

**Comment by scirner22** [comment]
Example of the associated env var configuration needed for tls

**Review by jtalis — APPROVED** [review]

**Review by leeduan — APPROVED** [review]
dumb question why prefer JAVA_OPTS over adding discrete envars?

**Comment by scirner22** [comment]
> dumb question why prefer JAVA_OPTS over adding discrete envars?

Is there a way to specify them as env vars? Here's the example I was using locally.

```bash
JAVA_OPTS=-Dserver.port=5080 -Dserver.ssl.enabled=true -Dserver.ssl.key-store-type=PKCS12 -Dserver.ssl.key-store=/keystore.p12 -Dserver.ssl.key-store-password=changeit -Dserver.ssl.protocol=TLS -Dserver.ssl.enabled-protocols=TLSv1.2
```

For some reason I couldn't get server.port to work as an env var in the applications.properties file. It would work when running directly with `bootRun` but never worked for changing from 8080 on the container route.

**Comment by leeduan** [comment]
> > dumb question why prefer JAVA_OPTS over adding discrete envars?
> 
> Is there a way to specify them as env vars? Here's the example I was using locally.
> 
> ```shell
> JAVA_OPTS=-Dserver.port=5080 -Dserver.ssl.enabled=true -Dserver.ssl.key-store-type=PKCS12 -Dserver.ssl.key-store=/keystore.p12 -Dserver.ssl.key-store-password=changeit -Dserver.ssl.protocol=TLS -Dserver.ssl.enabled-protocols=TLSv1.2
> ```
> 
> For some reason I couldn't get server.port to work as an env var in the applications.properties file. It would work when running directly with `bootRun` but never worked for changing from 8080 on the container route.

Hmm I haven’t tested it via container yet in omnibus. Definitely was able to adjust it to 8443 by overriding server.port and run over https. Probably not worth messing with to get it working for them. Plus this is flexible

**Comment by scirner22** [comment]
> > > dumb question why prefer JAVA_OPTS over adding discrete envars?
> > 
> > 
> > Is there a way to specify them as env vars? Here's the example I was using locally.
> > ```shell
> > JAVA_OPTS=-Dserver.port=5080 -Dserver.ssl.enabled=true -Dserver.ssl.key-store-type=PKCS12 -Dserver.ssl.key-store=/keystore.p12 -Dserver.ssl.key-store-password=changeit -Dserver.ssl.protocol=TLS -Dserver.ssl.enabled-protocols=TLSv1.2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For some reason I couldn't get server.port to work as an env var in the applications.properties file. It would work when running directly with `bootRun` but never worked for changing from 8080 on the container route.
> 
> Hmm I haven’t tested it via container yet in omnibus. Definitely was able to adjust it to 8443 by overriding server.port and run over https. Probably not worth messing with to get it working for them. Plus this is flexible

I didn't try the ssl vars because I already had this setup for the port, but it was very strange. I set `server.port=5080` directly in the application.properties and it worked like that when using `bootRun`, but building and running from the container defaulted back to `8080`.

**Pull request merged**
